config/routes.rb
Rails.application.routes.draw do
  root "messages#index"
  resources :messages, except: [:edit, :show, :update] do
    collection { get :import }
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :submiter

  validates_presence_of :name, :subject, :contents
  validates_associated :submiter
end

app/models/submiter.rb
# frozen_string_literal: true

class Submiter < ApplicationRecord
  has_many :messages
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

# messages request machine
class MessagesController < ApplicationController
  require 'csv'

  def index
    @messages = Message.all
  end

  def create
    message = MessageSerializer.new(message_params)
    if message.valid?
      CSV.open('storage/messages.csv', 'a') do |f|
        f << message_params.to_hash.fetch_values('name', 'email', 'subject', 'contents')
      end
      head :created
    else
      head :unprocessable_entity
    end
  end

  def import
    if Rails.env.production?
      ImportMessagesJob.perform_later
    else
      import_service = ImportMessagesService.new('storage/messages.csv')
      import_service.write_to_db
    end
  end

  def destroy
    message = Message.find_by_id(params[:id])
    message.try(:destroy)
    redirect_to messages_path
  end

  private

  def message_params
    params.permit(:id, :name, :email, :subject, :contents)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# main helper module for app
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommpeackTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<tr>
  <td><%= message.id %></td>
  <td><%= message.name %></td>
  <td><%= message.submiter.email %></td>
  <td><%= message.subject %></td>
  <td><%= message.contents %></td>
  <td><%= link_to 'destroy', message, data: {'turbo-method': :delete, turbo_confirm: 'Are you sure?' } %></td>
</tr>

app/views/messages/import.html.erb
<%= link_to 'Back', :back %>
<p>Import is started</p>

app/views/messages/index.html.erb
<%= link_to 'Import', import_messages_path %>
<%= link_to 'New message', new_message_path %>

<% if @messages.empty? %>
  <p>messages not found </p>
<% else %>
  <table>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Subject</th>
      <th>Contents</th>
      <th></th>
    </tr>
    <% @messages.each do |message| %>
      <%= render message %>
    <% end %>
  </table>
<%end%>

app/views/messages/new.html.erb
<%= form_tag '/messages', method: :post, class: 'stylized' do %>
  <%= label_tag :name %>
  <%= text_field_tag :name %>
  <%= label_tag :email %>
  <%= email_field_tag :email %>
  <%= label_tag :subject %>
  <%= text_field_tag :subject %>
  <%= label_tag :contents %>
  <%= text_field_tag :contents %>
  <%= submit_tag %>
<% end %>